version: "3.9"

services:

  app:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./web-app:/var/www

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - ./web-app:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app