services:

  api:
    build: ./MIApi
    container_name: fastapi_server
    ports:
      - "5050:5050"
    restart: always
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_y7RvXL4DMeHo@ep-dry-field-an7ram0t-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
      - GMAIL_USER=124050385@upq.edu.mx
      - GMAIL_APP_PASSWORD=jgjtnqwsoodoqpeh
      - TZ=America/Mexico_City
    volumes:
      - ./MIApi/app:/app/app

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: control_acceso
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d control_acceso"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    container_name: laravel_web
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=ep-dry-field-an7ram0t-pooler.c-6.us-east-1.aws.neon.tech
      - DB_PORT=5432
      - DB_DATABASE=neondb
      - DB_USERNAME=neondb_owner
      - DB_PASSWORD=npg_y7RvXL4DMeHo
      - TZ=America/Mexico_City
    volumes:
      - ./web-app/resources:/var/www/html/resources
      - ./web-app/app:/var/www/html/app
      - ./web-app/routes:/var/www/html/routes
      - ./web-app/storage:/var/www/html/storage
      - ./web-app/.env:/var/www/html/.env

volumes:
  db_data:
