services:

  api:
    build: ./MIApi
    container_name: fastapi_server
    ports:
      - "5050:5050"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/control_acceso

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: control_acceso
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d control_acceso"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    container_name: laravel_web
    ports:
      - "8000:8000"
    depends_on:
      api:
        condition: service_started
      db:
        condition: service_healthy
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=control_acceso
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres

volumes:
  db_data:
