FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
# Copiamos la carpeta App al contenedor
COPY ./App ./App
# Ejecutamos el servidor
CMD ["uvicorn", "App.main:app", "--host", "0.0.0.0", "--port", "8000"]